on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    # - name: Cache pip
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    # # this cache the platformio binaries and not the .pio folder
    # - name: Cache PlatformIO
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.platformio
    #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: https://github.com/actions/setup-python@v3

    - name: Install PlatformIO
      run: pip install platformio

    - name: Build the project
      run: platformio run

    - name: Test the project
      run: platformio check --fail-on-defect high
