export enum ButtonLabels {
  LOAD = "CHARGER",
  SAVE = "ENREGISTRER",
  START = "COMMENCER",
  CONTINUE = "CONTINUER",
}

export enum InputLabels {
  BREAK = "BREAK",
  SMALL_BLIND = "SMALL BLIND",
  BIG_BLIND = "BIG BLIND",
  ANTE = "ANTE",
  DURATION = "DURATION",
  STRUCTURE = "STRUCTURE",
  STACKS = "STACKS",
  REGISTRATION_MAX = "TEMPS D'INSCRIPTION MAX",
  MULTI_TABLE = "PLUSIEURS TABLES",
  COST_ENTRY = "COÛT D'ENTRÉE",
}

export enum InputEndTextLabels {
  MIN = "MIN",
  DOLLARD = "$",
  EURO = "€",
}
