name: Mirroring

on: [push, delete, pull_request]

jobs:
  push_to_public_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechMscProPromo2024/T-ESP-900-esp901-41057-Fettuccini-3.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_KEY }}